version: '3'
services:
  sensorthings-timeseries:
    container_name: sta-ts
    image: enocmartinez/sensorthings-timeseries:v0.2.1-alpine
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    healthcheck:
      test: curl --fail http://localhost:3000/Sensors || exit 1
      interval: 60s
      retries: 1
      timeout: 2s
    restart: unless-stopped